name: Docs Generator
on:
  push:
jobs:
  locale_gen:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - name: Prepare Flutter SDK
        uses: subosito/flutter-action@v1
      - run: flutter channel dev
        name: Switch Flutter channel
      - run: cd tools/docgen && flutter pub get
        name: Get dependencies
      - run: cd tools/docgen && dart bin/docgen.dart
        name: Convert Markdown to HTML
      - name: Deploy to GitHub pages
        run: |
          echo "docs.dahliaos.io" >> docs/CNAME
          git config user.name github-actions
          git config user.email "action@github.com"
          git --work-tree docs add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
