name: Create release

on:
  schedule:
    - cron: 0 12 * * 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set NOW
        run: | 
          echo "RELEASE_TAG=$(date +'%y%m%d')" >> $GITHUB_ENV
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: bump changes 
        run: |
          python tools/changes/bump_changes.py
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Creating Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_TAG  }}
          release_name: ${{ env.RELEASE_TAG }}
          body_path: .github/release.md
          draft: false
          prerelease: false
          
